language: smalltalk
sudo: true

# Select operating system(s)
os:
  - linux

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-6.0

env:
  - SMALLTALK_CI_TIMEOUT=40
cache:
  directories:
    - $SMALLTALK_CI_CACHE
