language: smalltalk
sudo: true

# Select operating system(s)
os:
  - linux

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-5.0

env:
- SMALLTALK_CI_TIMEOUT=40

install: 
  - sudo apt-get install espeak gnustep-gui-runtime festival speech-dispatcher